-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: v0.8.0
    hooks:
    - id: check-yaml
    - id: check-case-conflict
    - id: check-byte-order-marker
    - id: check-symlinks
    - id: forbid-new-submodules
    - id: trailing-whitespace
- repo: https://github.com/willthames/ansible-lint.git
  sha: v3.4.15
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$
      args: ['--exclude=.travis.yml', '-x', 'ANSIBLE0016']
